name: Publish App to S3 dev, staging or production

on:
  release:
    types: 
      - published

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: TEST
        run: 

  build-and-publish-dev:
    if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '-dev')
    uses: siri-aws-web-app/thoth-workflows/.github/workflows/publish-frontend.yml@v1.0.9
    with:
      AWS_REGION: "eu-central-1"
      AWS_ROLE_TO_ASSUME: "arn:aws:iam::360532638835:role/github-freyr"
      S3_URI: "s3://development.siri-freyr.xyz"
      ENVIRONMENT: "development"

  build-and-publish-stag:
    if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '-stag')
    uses: siri-aws-web-app/thoth-workflows/.github/workflows/publish-frontend.yml@v1.0.9
    with:
      AWS_REGION: "eu-central-1"
      AWS_ROLE_TO_ASSUME: "arn:aws:iam::525284627566:role/github-freyr"
      S3_URI: "s3://staging.siri-freyr.xyz"
      ENVIRONMENT: "staging"
  
  build-and-publish-prod:
    if: startsWith(github.ref, 'refs/tags/v') && !endsWith(github.ref, '-dev') && !endsWith(github.ref, '-stag')
    uses: siri-aws-web-app/thoth-workflows/.github/workflows/publish-frontend.yml@v1.0.9
    with:
      AWS_REGION: "eu-central-1"
      AWS_ROLE_TO_ASSUME: "arn:aws:iam::875944587789:role/github-freyr"
      S3_URI: "s3://siri-freyr.xyz"
      ENVIRONMENT: "production"