name: Publish App to S3 dev, staging or production

on:
  release:
    types: 
      - published
  push:
    tags:
      - '*'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish-dev:
    if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '-dev')
    uses: siri-aws-web-app/thoth-workflows/.github/workflows/publish-frontend.yml@v1.0.7
    with:
      AWS_REGION: "eu-central-1"
      AWS_ROLE_TO_ASSUME: "arn:aws:iam::360532638835:role/github-freyr"
      S3_URI: "s3://development.siri-freyr.xyz"

  build-and-publish-stag:
    if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '-stag')
    uses: siri-aws-web-app/thoth-workflows/.github/workflows/publish-frontend.yml@v1.0.7
    with:
      AWS_REGION: "eu-central-1"
      AWS_ROLE_TO_ASSUME: "arn:aws:iam::525284627566:role/github-freyr"
      S3_URI: "s3://staging.siri-freyr.xyz"
  
  build-and-publish-prod:
    if: startsWith(github.ref, 'refs/tags/v') && !endsWith(github.ref, '-dev') && !endsWith(github.ref, '-stag')
    uses: siri-aws-web-app/thoth-workflows/.github/workflows/publish-frontend.yml@v1.0.7
    with:
      AWS_REGION: "eu-central-1"
      AWS_ROLE_TO_ASSUME: "arn:aws:iam::875944587789:role/github-freyr"
      S3_URI: "s3://siri-freyr.xyz"